// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTvX4mvMAp2XfdjYr-uY_aPGWiVQ7nVlk',
    appId: '1:368195730231:web:55f656ce53075f0306b8b2',
    messagingSenderId: '368195730231',
    projectId: 'smilewater-24a5f',
    authDomain: 'smilewater-24a5f.firebaseapp.com',
    storageBucket: 'smilewater-24a5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJ-40h2M-8ObDpd792ZwdQL12-kzVDFo',
    appId: '1:368195730231:android:5d241705031a10b506b8b2',
    messagingSenderId: '368195730231',
    projectId: 'smilewater-24a5f',
    storageBucket: 'smilewater-24a5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuE4G1156sXgwgnv3loikmPJ8wXHvDriA',
    appId: '1:368195730231:ios:d428e0168b55ff8406b8b2',
    messagingSenderId: '368195730231',
    projectId: 'smilewater-24a5f',
    storageBucket: 'smilewater-24a5f.firebasestorage.app',
    iosBundleId: 'com.example.smilewater2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuE4G1156sXgwgnv3loikmPJ8wXHvDriA',
    appId: '1:368195730231:ios:d428e0168b55ff8406b8b2',
    messagingSenderId: '368195730231',
    projectId: 'smilewater-24a5f',
    storageBucket: 'smilewater-24a5f.firebasestorage.app',
    iosBundleId: 'com.example.smilewater2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTvX4mvMAp2XfdjYr-uY_aPGWiVQ7nVlk',
    appId: '1:368195730231:web:234869207267066906b8b2',
    messagingSenderId: '368195730231',
    projectId: 'smilewater-24a5f',
    authDomain: 'smilewater-24a5f.firebaseapp.com',
    storageBucket: 'smilewater-24a5f.firebasestorage.app',
  );
}
